export {
  STORAGE_KEYS,
  SUPABASE_KEY,
  SUPABASE_URL,
  GOOGLE_WEB_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID,
  GOOGLE_ANDROID_CLIENT_ID,
  DEFAULT_PAGE_SIZE,
  COMMENTS_PAGE_SIZE,
  MAX_FILE_SIZE_MB,
  MAX_FILE_SIZE_BYTES,
  ALLOWED_FILE_TYPES,
  MENTION_REGEX,
  ANIMATION,
} from './config';

export {
  TASK_STATUSES,
  TASK_PRIORITIES,
  STATUS_LABELS,
  ROLE_LABELS,
  ONBOARDING_SLIDES,
} from './data';
